<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugSymbols>false</DebugSymbols>
		<DebugType>None</DebugType>
	</PropertyGroup>


	<ItemGroup>
    <PackageReference Include="Flow.Launcher.Plugin" Version="5.3.0" />
  </ItemGroup>

</Project>
